/**
 * Created by Mitchell Parekh on 10/31/2016.
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem02 {
    public static void main(String[] args) {
        int sol = solution();
        System.out.println("The sum of the even-valued terms in the Fibonacci sequence whose " +
                "values do not exceed four million is: " + sol + ".");
    }

    public static int solution() {
        return 0;
    }

}
